config/routes.rb
Rails.application.routes.draw do

  devise_for :users, :skip => [:registrations]
  as :user do
    get 'users/edit' => 'devise/registrations#edit', :as => 'edit_user_registration'
    put 'users' => 'devise/registrations#update', :as => 'user_registration'
  end

  resources :user_types
  resources :users#, except: [:show, :destroy]
  get 'home/index'
  root to: 'user_types#index'

end

app/controllers/user_types_controller.rb
class UserTypesController < ApplicationController
  before_action :set_user_type, only: [:show, :edit, :update, :destroy]

  # GET /user_types
  # GET /user_types.json
  def index
    @user_types = UserType.page(params[:page]).per(6)
  end

  # GET /user_types/1
  # GET /user_types/1.json
  def show
  end

  # GET /user_types/new
  def new
    @user_type = UserType.new
  end

  # GET /user_types/1/edit
  def edit
  end

  # POST /user_types
  # POST /user_types.json
  def create
    @user_type = UserType.new(user_type_params)

    respond_to do |format|
      if @user_type.save
        format.html { redirect_to @user_type, notice: t('flash.actions.create.notice') }
        format.json { render :show, status: :created, location: @user_type }
      else
        format.html { render :new }
        format.json { render json: @user_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /user_types/1
  # PATCH/PUT /user_types/1.json
  def update
    respond_to do |format|
      if @user_type.update(user_type_params)
        format.html { redirect_to @user_type, notice: t('flash.actions.update.notice') }
        format.json { render :show, status: :ok, location: @user_type }
      else
        format.html { render :edit }
        format.json { render json: @user_type.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /user_types/1
  # DELETE /user_types/1.json
  def destroy
    @user_type.destroy
    respond_to do |format|
      format.html { redirect_to user_types_url, notice: t('flash.actions.destroy.notice') }
      format.json { head :no_content }
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_user_type
    @user_type = UserType.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def user_type_params
    params.require(:user_type).permit(:name, :description, :authorizeDiscount, :commissionPercentage)
  end
end

app/helpers/user_types_helper.rb
module UserTypesHelper
end

app/views/user_types/_form.html.erb
<div class="container">
  <%= form_for(@user_type) do |f| %>
  <% if @user_type.errors.any? %>

  <div class="alert alert-warning alert-dismissible" role="alert">
    <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
    <h4><%= pluralize(@user_type.errors.count, 'erro') %>
      <%= t("impedir", count: @user_type.errors.count) %>
      <%=t :of_save %>.
    </h4>
    <ul>
      <% @user_type.errors.full_messages.each do |message| %>
      <li><%= message %>.</li>
      <% end %>
    </ul>
  </div>

  <% end %>
  <div class="form-group">
    <%= f.label :name %><br>
    <%= f.text_field :name, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :description %><br>
    <%= f.text_area :description, class:"form-control" %>
  </div>
  <div class="form-group">
    <%= f.label :authorizeDiscount %>
    <%= f.check_box :authorizeDiscount, class:"checkbox" %>
  </div>
  <div class="form-group">
    <%= f.label :commissionPercentage %><br>
    <%= f.number_field :commissionPercentage,step: 0.5, class:"form-control" %>
  </div>
  <div class="actions">
    <%= button_tag( :class => "btn btn-success") do %>
    <i class="fa fa-save"></i>
    <%=t :save %>
    <% end %>
    <%= link_to user_types_path, class: "btn btn-default" do %>
    <i class="fa fa-ban"></i>
    <%=t :cancel %>
    <% end %>
  </div>
  <% end %>
</div>

app/views/user_types/edit.html.erb
<div class="container">
<h1><%=t :edit_user_type %></h1>
<%= render 'form' %>

app/views/user_types/index.html.erb
<div class="container">
  <% if notice %>
  <script>
    $.notify("<%= notice %>", {
      className:'info',
      clickToHide: true,
      autoHide: true,
      globalPosition: 'top center'
    });
  </script>
</div>

<% end %>
<h1>
  <%= t("activerecord.models.user_type", count: @user_types.count) %>
</h1>
<div class="container" align="right">
  <%= link_to new_user_type_path, class: "btn btn-success" do %>
  <i class="fa fa-plus"></i>
  <%=t :new_user_type %>
  <% end %>
</div>
<table class="table">
  <thead>
    <tr>
      <th>
        <%= UserType.human_attribute_name("name")%>
      </th>
      <th>
        <%= UserType.human_attribute_name("description")%>
      </th>
      <th colspan="3"></th>
    </tr>
  </thead>
  <tbody>
    <% @user_types.each do |user_type| %>
    <tr>
      <td>
        <%= user_type.name %>
      </td>
      <td>
        <%= user_type.description %>
      </td>
      <td>
        <%= link_to user_type, class: "btn btn-info" do %>
        <i class="fa fa-eye"></i>
        <%=t :show %>
        <% end %>
      </td>
      <td>
        <%= link_to edit_user_type_path(user_type), class: "btn btn-default" do %>
        <i class="fa fa-edit"></i>
        <%=t :edit %>
        <% end %>
      </td>
      <td>
        <%= link_to user_type, method: :delete, data: { confirm: t('are_you_sure') } , class: "btn btn-danger" do %>
        <i class="fa fa-trash"></i>
        <%=t :delete %>
        <% end %>
      </td>
    </tr>
    <% end %>
  </tbody>
</table>
<br>
</div>
<div class="container" align="center">
  <%= paginate @user_types %>
</div>

app/views/user_types/new.html.erb
<div class="container">
<h1><%=t :new_user_type %></h1>

<%= render 'form' %>

app/views/user_types/show.html.erb
<div class="container">
  <div class="row">
    <div class="col-sm-6 col-sm-offset-3">
      <% if notice %>
      <div class="alert alert-success alert-dismissible role="alert">
        <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <%= notice %>
      </div>
      <% end %>
      <h3>
        <%= t("activerecord.models.user_type", count: 1) %>
      </h3>
      <div class="well">
        <p>
          <strong>
            <%= UserType.human_attribute_name("name")%>:</strong>
            <%= @user_type.name %>
          </p>
          <p>
            <strong>
              <%= UserType.human_attribute_name("description")%>:</strong>
              <%= @user_type.description %>
            </p>
            <p>
              <strong>
                <%= UserType.human_attribute_name( "authorizeDiscount")%>:</strong>
                <%=human_boolean(@user_type.authorizeDiscount)  %>
              </p>
              <p>
                <strong>
                  <%= UserType.human_attribute_name("commissionPercentage")%>:</strong>
                  <%= @user_type.commissionPercentage %>
                </p>
              </div>
              <%= link_to edit_user_type_path(@user_type), class: "btn btn-info" do %>
              <i class="fa fa-edit"></i>
              <%=t :edit %>
              <% end %>
              <%= link_to user_types_path, class: "btn btn-default" do %>
              <i class="fa fa-arrow-left"></i>
              <%=t :back %>
              <% end %>
    </div>
  </div>
</div>